didier: True #for raccoon energy

### general stuff ###

command: "run_download"
use_gpu: False
save_path: "/models/mnist_classifier.pt" #given wrp to /src
same_data_size_everywhere: True #
small: False

common:
  size_train: 1000
  size_val: 100


### config for training cnn###
train_cnn:
  hyperparameters:
    lr: 0.1
    epochs: 24
    batch_size: 64
  criterion: "BCELoss" #must be named exactly as in torch.nn.
  save_path: "models/CNN_classifier.pt"

### config for Evaluation ###
evaluate:
  verbose: True

### config for training huggingface ###
train_transformer:
 input_filepath: /data/processed
 output_filepath: /models
 size_train: 70
 size_val: 30
 hyperparameters:
  evaluation_strategy: "epoch"
  logging_steps: 100
  learning_rate: 2.0e-5
  per_device_train_batch_size: 16
  per_device_eval_batch_size: 16
  num_train_epochs: 3
  weight_decay: 0.01


### config for predicting huggingface ###
eval_transformer:
  data_filepath: "/data/processed"
  model_filepath: "/models"
  size_train: 70
  size_val: 30
  hyperparameters:
    evaluation_strategy: "epoch"
    logging_steps: 100
    learning_rate: 2.0e-5
    per_device_train_batch_size: 16
    per_device_eval_batch_size: 16
    num_train_epochs: 3
    weight_decay: 0.01
### config for loading processed data ###
process_data:
  size_train: 70
  size_val: 30
  input_filepath: "/data/raw"
  output_filepath: "/data/processed"

### config for making dataset ###
run_download:
  size_train: 70
  size_val: 30
  output_filepath: "/data/raw"

### hydra config ###
defaults:  
  - override hydra/job_logging: colorlog  
  - override hydra/hydra_logging: colorlog